# Setup
title:        黑之庭院
tagline:      健全的灵魂寄宿于健全的精神和健全的肉体之中
baseurl:      ""
paginate:     1
locale:       "en"

# About/contact
author:
  name:       划水的柴犬
  url:        https://xiebaiting.github.io 

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown